PASSWORD = "coop"

[gcp_service_account]
type = "service_account"
project_id = "decent-lambda-476404-q4"
private_key_id = "3295b156c0eac674170832d640e77b54f09aa147"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD+tWio4D0CJkIp
RpowGHAWjIoUy91KCNo6RRn8eCHrPAQlYBWzu87zq7LELCZvFVgGNNIIDX5ry5TG
aCS9r7jxYL4votTaXvCdjqJP95JvHhajE4TVHAb5OTnuAtI8HbiB8jdZc0PoOjuO
/JEMZGVkTpNLKQuUFMKYzQBhayCc/E634AbnLOVWnyyqeSr/AXsMfNMbBjPEEl7I
NliN8Y0g+u4ANlxcI8OsjHvwl5htfl2q3dfZMgsXBefz9m69bHOUH8buvUFJ58N4
T2wybvH/DmoPsypQGPG474XRRD9oEYHOerzgVoFvpCQWHVKXMY88c5yynHvmkulF
tkMNIu7BAgMBAAECggEAI3JamNnwE5sAbR8auSPFgZXYZ5GBf9qgiChyt9x+F+8X
wp3PF17FK8sSy1M7nAzz3ZU/P4ilNdo0n7IBnvZT/h+RCC8YgTViNgMSGp/hHJ6q
1tISE9hdLhTlN3bkDCK0uTzcsBGm+ywTetAyXW+hXqbCv9x79IU5Gau56FTQypfZ
R66ml5zvOvDbGjUU+pgZP/YafcV42BxCoIgkFnzK+vVtNoeXl9c7GGCaADEgFFFN
uzozhnGtHqw6+glvV5OXxobo7JHCu3m5qsO0kHBg93FHR9FveiswDGFYp0xOrUya
oWRHxgLhaJMZzLatZqLs1XKTak1kVy5X/c6+eowcqwKBgQD/yoF6J3/XShwIpV5i
esHszB/W9vLH9CsKjqWxvZ9V5IQtlD1MRqleIKWZ2ONSK5XybNXgV3azETtt5Sd7
VkPpSkZS7ODFC1j2mOqK66RzFsLj38oDnjt3nJ9VmzkLxKejwU2FzfK/3My+W59C
PwOcgXbe99rBlCU291XGX7wRmwKBgQD+6q07hlS9xqzSSESHtxepFVaO/EojQJw9
Hb3TIWov8gAZx41jWfTcpxhJksuwqtFUwiqGuRA/6nhmX82M/oUy6+YD5tcLqyDk
vsvBoAXV4hIo3slMitvw7/COumqiwlLBPTf19VzE8W60c8KXF9nekRG9hb2R1LfK
+WgSUS4E0wKBgQCf3vDX6VIkvAQTf1AjmvgTyWzpDUWmpbw1B/0Vvx+ULpRSbIF3
Z/65fwwhwQYrOGSqtU1jvybIOq/7OqtXkg42BB85+yVs4m/DCMYm96q75/D9PcTk
SASA+No5Rh/8c/gXCF0skRD0y8sH+vnqDLp0GhKyvxTxwmcUGLh6mSFRmwKBgEtX
vT+8oks871NvfKHIIbwdzGmSc68bp5IAulwuoh3tns3/xvA4ZEDbOjh0pLNgqWIt
yTfsdrsNZ+yKIEyt5Vx5kJBSp/iQ6bXyFnLyAweGO+vMfR6cZAlAQY9N1bqpSKBI
ocOWc4bZ/Ohk1nyl1gUMR3wGjVMO1gutz26qg7l1AoGBAMBB/gac1cpR3/pInDik
+8+7qD6phJC28AbQ1vwj/N4NzdM1gs/wLrxNgrCfNejyHh4yQOGzMDq1I6oH2nev
bQr1JeKvpzJIEtV0EDSDaaHy//mWeM36E5/OS06kzxqC48qm3tzl6Ft618gj6W1n
wi3n4x20N+4s/zsjMPBrmHaL
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@decent-lambda-476404-q4.iam.gserviceaccount.com"
client_id = "106702312391381654967"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40decent-lambda-476404-q4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
